name: Build and Deploy
on:
  push:
    branches:
      - main # Asegúrate de que esto coincida con la rama donde subes tus cambios
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Agrega pasos para instalar dependencias y construir tu proyecto si es necesario
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build # Asegúrate de que tu proyecto tiene un script de build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist # Asegúrate de que esto coincida con el directorio de salida de tu build
